### ISSUE TITLE
Roadmap 4.0.0

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#120]
# 🚀 So that's a wrap on the 3.0.0 release!

Well done to all those involved. I'd like to welcome a load of new maintainers to the project who I can't thank enough for their hard work and effort on the project.

@asiyani 
@ironprice91 
@vcapretz 
@SaraVieira 

The big striking feature for 3.0.0 was a brand new redesign done by @SaraVieira . There was also the login with github system that was by @asiyani.

Looking good ESFiddle 😎 ![Woo!](https://i.giphy.com/XreQmk7ETCak0.gif)

# What's for 4.0.0? 💡 
Without further ado, here is the issues we have for **4.0.0**. There is room for change here. There is a lot of low hanging fruit in this release so perfect for first-timers! If you know someone who is looking to contribute on open source then let them know!

- [x] Fix Google PSI issues - issue is [here](https://github.com/esfiddle/esfiddle/issues/113) and [here](https://github.com/esfiddle/esfiddle/issues/112)
- [x] Improving the about page - issue is [here](https://github.com/esfiddle/esfiddle/issues/114)
- [x] Fix the navbar being inconsistent on the blog - issue is [here](https://github.com/esfiddle/esfiddle/issues/115)
- [ ] Improve documentation for getting started - issue is here
- [ ] Add new doc for FAQ of common problems encountered when starting to contribute - issue is [here](https://github.com/esfiddle/esfiddle/issues/116)
- [ ] Add loading of NPM libraries from dropdown - issue is [here](https://github.com/esfiddle/esfiddle/issues/46) - **Very** excited about this one
- [x] Make the line between the code and console more visible when in dark mode with a dark code theme (or a white theme code window and light mode console) - issue is [here](https://github.com/esfiddle/esfiddle/issues/117)
- [ ] Export as Gist functionality - issue is [here](https://github.com/esfiddle/esfiddle/issues/98)
- [x] Change Favicon to the new logo on the blog - issue is [here](https://github.com/esfiddle/esfiddle/issues/118)
- [x] Make profiles publicly accessible - issue is [here](https://github.com/esfiddle/esfiddle/issues/119)
- [ ] Add titles and descriptions to fiddles - issue is [here](https://github.com/esfiddle/esfiddle/issues/102)

### But Josh, what are you doing you lazy git?
Well, for full disclosure here is the list of things I'm planning on doing.
- [ ] Setup a slack invite server so people can request an invite to the slack
- [x] Configure heroku review apps for PR's
- [ ] Write FAQ content for the about page
- [ ] Add documentation for maintainers on releasing and accepting new PR's
- [ ] Update the vision document
- [ ] Write release notes for 3.0.0 release
- [ ] Various SEO improvements - @SaraVieira is also helping me with this
- [ ] Finally take a look into OpBeat

As always if you have ideas or suggestions then please feel free to comment below.
