### ISSUE TITLE
Roadmap - v2.0.0

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#47]
This is the primary issue outlining everything that will be done for the 2.0.0 release. This will ideally be completed in 6 weeks or less.

The main goal of this release is to add github signin and saves with fiddles. Future functionality that stems from this will come in later releases.

**UI/UX Changes**
- [x] Change the editors to fill the screen. Move over to use flexbox
- [ ] Improve the mobile site rendering, get a good score on the https://search.google.com/search-console/mobile-friendly test

**Backend**
- [x] Add github signin, save fiddles with a userId - active PR is [here](https://github.com/esfiddle/esfiddle/pull/44)
- [x] Cache images with express to address final page speed insights issue

**Community**
- [x] Improve documentation further, make it as easy as possible for people to get the site running locally.
- [x] Break issues down into smaller chunks to allow new contributors to work on bite-sized chunks of features or bug fixes.

**Comment by asiyani** [comment]
looks good.. I think we need to add  few things to UI/UX like 
 -> login /logout button
-> section on website where we can display user name who wrote that fiddle. (only if that user was logged in)  this is good when a guest user is viewing someone else fiddle.  
-> Not sure if we should display extra info related to github on our website like no. of repositories ...

**Comment by joshghent** [comment]
Updated the issue with all the issues that are now complete.
Thanks everyone!

**Comment by joshghent** [comment]
Ok we haven't quite completed everything but I think this is a good place to wrap up and release. We want get all the new shiny features that have been lovingly worked on into the hands of the users. 

I'm going to close this off and mark the current development branch state as 2.0.0.

Thank you all for your hard work
