### ISSUE TITLE
Roadmap 3.0.0 - The big code clean up!

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#66]
We got nearly all the features we wanted for version 2.0.0 done and released. Well done to everyone who contributed. It's amazing to see this little project turn into something with a great set of people hard at work on it! **Keep up the good work. And tell your friends!**

My reaction when we get new PR's ![Woo!](https://media.giphy.com/media/azxKobAo7JnO0/giphy.gif)

### **Anyway...**

In the coming month (not 6 weeks), I think we should aim for the following: The theme of this release is to overhaul the code and redesign. This will mean pretty much that we have a feature freeze whilst we clean up the code, redesign the site and fine tune it so that it's more user friendly and easier to maintain. So roll up your sleeves and grab your mop and buckets cus it's refactor time 😆 

* [ ] Add front end tests - issue is [here](https://github.com/esfiddle/esfiddle/issues/43)
* [ ] Add front end regression tests - issue is [here](https://github.com/esfiddle/esfiddle/issues/78)
* [x] Rewrite the main client JS in ES6+ - issue is [here](https://github.com/esfiddle/esfiddle/issues/64)
* [x] Improve the score on the Google mobile-friendly test - issue is [here](https://github.com/esfiddle/esfiddle/issues/56)
* [x] Sort the folder structure - issue is [here](https://github.com/esfiddle/esfiddle/issues/55)
* [ ] Make new design documentation - issue is [here](https://github.com/esfiddle/esfiddle/issues/53)
* [ ] Add new docs for the coding style, such as naming conventions
* [x] Dynamically show the login/logout buttons - issue is [here](https://github.com/esfiddle/esfiddle/issues/49)
* [x] Redesign the login area [here](https://github.com/esfiddle/esfiddle/issues/83)
* [x] Redesign the blog  [here](https://github.com/esfiddle/esfiddle/issues/82)
* [x] Split the app.js routes into separate files - issue is [here](https://github.com/esfiddle/esfiddle/issues/73)
* [ ] Add functionality to save names and descriptions for fiddles when you are logged in.
* [x] Add new example code - issue is [here](https://github.com/esfiddle/esfiddle/issues/74)

This is not a complete list and it might be subject to change (I have a couple of things I might throw in here)

As always, if you **have any suggestions or questions** then let me know here. We are very open to ideas!

**Comment by SaraVieira** [comment]
🎉 Awesome goals @joshghent !

**Comment by asiyani** [comment]
We also needs to add name or description for saved fiddles. (only for logged in users) 
At the moment user profile shows just a fiddle number, when you have multiple fiddle saved its difficult to find out which one is which.

**Comment by joshghent** [comment]
@asiyani Great idea - added

**Comment by SaraVieira** [comment]
@joshghent please add both issue of the tests here please :happy

**Comment by joshghent** [comment]
Ok we didn't quite get round to the front-end regression testing but we've added lots of new things! I'll close this off so we can head for the next release and get some new issues active here. Great work to everyone! 👍 👏
